# Generated by Django 5.0.6 on 2026-07-19 20:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundiProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True)),
                ('coverage_areas', models.JSONField(blank=True, default=list, help_text="List of Nairobi neighbourhoods served, e.g. ['Parklands', 'Westlands'].")),
                ('years_of_experience', models.PositiveSmallIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('credential_body', models.CharField(blank=True, choices=[('nca', 'National Construction Authority'), ('epra', 'Energy and Petroleum Regulatory Authority')], max_length=10)),
                ('credential_number', models.CharField(blank=True, max_length=50)),
                ('verification_status', models.CharField(choices=[('unsubmitted', 'Not Submitted'), ('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unsubmitted', max_length=15)),
                ('verification_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('completed_jobs_count', models.PositiveIntegerField(default=0)),
                ('trust_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fundi_profiles',
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'portfolio_images',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('requires_regulatory_credential', models.BooleanField(default=False, help_text='True for categories where NCA/EPRA verification is expected (e.g. Electrical, Masonry).')),
                ('icon', models.CharField(blank=True, help_text='Icon identifier for the frontend.', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'service categories',
                'db_table': 'service_categories',
                'ordering': ['name'],
            },
        ),
    ]
