# Generated by Django 5.0.6 on 2026-07-19 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fundiprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fundi_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images', to='providers.fundiprofile'),
        ),
        migrations.AddField(
            model_name='fundiprofile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='providers', to='providers.servicecategory'),
        ),
        migrations.AddIndex(
            model_name='fundiprofile',
            index=models.Index(fields=['verification_status'], name='fundi_profi_verific_81b6c8_idx'),
        ),
        migrations.AddIndex(
            model_name='fundiprofile',
            index=models.Index(fields=['is_available'], name='fundi_profi_is_avai_11c072_idx'),
        ),
    ]
