# Generated by Django 5.0.6 on 2026-07-19 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_body', models.CharField(max_length=10)),
                ('credential_number', models.CharField(max_length=50)),
                ('is_match', models.BooleanField()),
                ('status', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=50)),
                ('raw_response', models.JSONField(default=dict)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by_admin', models.BooleanField(default=False, help_text='Set once an admin has looked at this check and made a final decision.')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_checks', to='providers.fundiprofile')),
            ],
            options={
                'db_table': 'verification_checks',
                'ordering': ['-checked_at'],
            },
        ),
    ]
